import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function GET() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Fetch user and memory profile
  const { data: userData } = await supabase
    .from('users')
    .select('name, email')
    .eq('id', user.id)
    .single();

  const { data: profile } = await supabase
    .from('memory_profiles')
    .select('*')
    .eq('user_id', user.id)
    .single();

  if (!profile) {
    return NextResponse.json({ error: 'Profile not found' }, { status: 404 });
  }

  // Generate markdown
  const markdown = generateMarkdown(profile, userData);

  return new NextResponse(markdown, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${profile.display_name || 'profile'}.md"`,
    },
  });
}

function generateMarkdown(
  profile: {
    display_name: string;
    headline?: string | null;
    location?: string | null;
    work_experience?: Array<{
      company: string;
      title: string;
      start_date: string;
      end_date?: string | null;
      description?: string | null;
      is_current?: boolean;
    }>;
    skills?: string[];
    can_offer?: string[];
    looking_for?: string[];
    current_goals?: string[];
    interests?: string[];
    values?: string[];
    intents?: string[];
  },
  userData?: { name?: string; email?: string } | null
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${profile.display_name}`);
  lines.push('');

  if (profile.headline) {
    lines.push(`> ${profile.headline}`);
    lines.push('');
  }

  // About
  lines.push('## About');
  if (profile.location) {
    lines.push(`- **Location:** ${profile.location}`);
  }
  if (profile.current_goals && profile.current_goals.length > 0) {
    lines.push(`- **Current Goals:** ${profile.current_goals.join(', ')}`);
  }
  if (userData?.email) {
    lines.push(`- **Email:** ${userData.email}`);
  }
  lines.push('');

  // Professional
  if (
    (profile.work_experience && profile.work_experience.length > 0) ||
    (profile.skills && profile.skills.length > 0)
  ) {
    lines.push('## Professional');
    lines.push('');

    if (profile.work_experience && profile.work_experience.length > 0) {
      lines.push('### Experience');
      for (const exp of profile.work_experience) {
        const dateRange = exp.is_current
          ? `${exp.start_date} - Present`
          : `${exp.start_date} - ${exp.end_date || 'N/A'}`;
        lines.push(`- **${exp.title}** at ${exp.company} (${dateRange})`);
        if (exp.description) {
          lines.push(`  - ${exp.description}`);
        }
      }
      lines.push('');
    }

    if (profile.skills && profile.skills.length > 0) {
      lines.push('### Skills');
      lines.push(profile.skills.map((s) => `\`${s}\``).join(' '));
      lines.push('');
    }
  }

  // What I Offer
  if (profile.can_offer && profile.can_offer.length > 0) {
    lines.push('## What I Can Offer');
    for (const item of profile.can_offer) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  // What I'm Looking For
  if (profile.looking_for && profile.looking_for.length > 0) {
    lines.push("## What I'm Looking For");
    for (const item of profile.looking_for) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  // Personal
  if (
    (profile.interests && profile.interests.length > 0) ||
    (profile.values && profile.values.length > 0)
  ) {
    lines.push('## Personal');
    lines.push('');

    if (profile.interests && profile.interests.length > 0) {
      lines.push('### Interests');
      lines.push(profile.interests.join(', '));
      lines.push('');
    }

    if (profile.values && profile.values.length > 0) {
      lines.push('### Values');
      lines.push(profile.values.join(', '));
      lines.push('');
    }
  }

  // Relationship Types
  if (profile.intents && profile.intents.length > 0) {
    lines.push('## Open to Connect');
    const intentLabels: Record<string, string> = {
      professional: 'Professional networking',
      dating: 'Dating',
      friendship: 'Friendship',
    };
    for (const intent of profile.intents) {
      lines.push(`- ${intentLabels[intent] || intent}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('*Generated by [Nomi](https://getnomi.me) - Your digital world manual*');

  return lines.join('\n');
}
